### PR TITLE
Add support for named types

### PR DESCRIPTION
**Pull request by markogresak**
The #1 got me thinking. More specifically, the comment about exporting constants, since that really is an unusual practice. 
This PR is adding support for named skin tones, for example:

``` js
skinTone('👍', 'dark');
//=> '👍🏾
skinTone('👍', 'dark brown');
//=> '👍🏿
```

Full description in readme at the bottom. Basically anything that `lodash.snakecase` can convert to one of the constant names is acceptable as name. 

On a side note, also added check and tests for unexpected `type`, which is any number not in range 0..5, a string not matching any of the constants or any other type.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I actually prefer the constants. With those you only really accept one type, a number, but can optionally use constants to make the value clearer. And it's a syntax error if you spell it incorrectly.

**Comment by sindresorhus** [comment]
Closing in favor of #1. Sorry about the wasted effort.

**Comment by markogresak** [comment]
> And it's a syntax error if you spell it incorrectly.

In this case, TypeError would occur. 

> Sorry about the wasted effort.

No need to apologize, it was a fun thing to do for a change and I've learned something new 😄

**Comment by sindresorhus** [comment]
> In this case, TypeError would occur.

Only at runtime though. With constants linters will catch it too.

**Comment by markogresak** [comment]
Good point.  Didn't think about linters.

**Pull request closed without merging**
